# Generated by Django 3.1.2 on 2020-10-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truelines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registertable',
            old_name='mobno',
            new_name='mobile',
        ),
    ]
