# Generated by Django 3.1.2 on 2020-11-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelines', '0003_auto_20201031_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='mobileno',
            field=models.CharField(max_length=11),
        ),
    ]
