# Generated by Django 3.1.2 on 2020-11-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelines', '0004_auto_20201031_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
