# Generated by Django 3.1.2 on 2020-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelines', '0005_auto_20201101_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertable',
            name='email',
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
