# Generated by Django 3.1.2 on 2020-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelines', '0006_registertable_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('quotes', models.CharField(max_length=500)),
                ('mobileno', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=16)),
            ],
        ),
    ]
