# Generated by Django 3.1.2 on 2020-11-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelines', '0007_quotespost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotespost',
            name='quotes',
            field=models.TextField(max_length=500),
        ),
    ]
